import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;
/*
console.log("SOURCEMAP=" + process.env.SOURCEMAP);
console.log("NO_MINIFY=" + process.env.NO_MINIFY);
console.log("DROP_LOGS=" + process.env.DROP_LOGS);
console.log("ANALYZE_META=" + process.env.ANALYZE_META);
*/
const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: process.env.SOURCEMAP !== "1" ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: process.env.NO_MINIFY !== "1",
	metafile: true,
	drop: process.env.DROP_LOGS === "1" ? ["console", "debugger"] : [], // Removes logs and debuggers from build
});

if (prod) {
	const result = await context.rebuild();

	// Save metafile as file
	if (result.metafile) {
		fs.writeFileSync("meta.json", JSON.stringify(result.metafile, null, 2));
		if (process.env.ANALYZE_META === "1") {
			// Optional: Bundle size breakdown in terminal
			console.log(await esbuild.analyzeMetafile(result.metafile));
		}
	}
	await context.dispose();
	process.exit(0);
} else {
	await context.watch();
}
